//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: hackz.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Greeter_GreeterClient, then call methods of this protocol to make API calls.
internal protocol Greeter_GreeterClientProtocol: GRPCClient {
  func sayHello(
    _ request: Greeter_HelloRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Greeter_HelloRequest, Greeter_HelloReply>

}

extension Greeter_GreeterClientProtocol {

  /// Sends a greeting
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sayHello(
    _ request: Greeter_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Greeter_HelloRequest, Greeter_HelloReply> {
    return self.makeUnaryCall(
      path: "/greeter.Greeter/SayHello",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Greeter_GreeterClient: Greeter_GreeterClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the greeter.Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Greeter_GreeterProvider: CallHandlerProvider {
  /// Sends a greeting
  func sayHello(request: Greeter_HelloRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Greeter_HelloReply>
}

extension Greeter_GreeterProvider {
  internal var serviceName: Substring { return "greeter.Greeter" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "SayHello":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.sayHello(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

